# Generated by Django 3.1 on 2020-10-26 14:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201023_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='First name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last name')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('address', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Address')),
                ('status', models.CharField(choices=[('new', 'New order'), ('in_progress', 'Order is in progress'), ('is_ready', 'Order is ready'), ('completed', 'Order is completed')], default='new', max_length=100, verbose_name='Order status')),
                ('buying_type', models.CharField(choices=[('self', 'Self delivery'), ('delivery', 'Delivery')], default='self', max_length=100, verbose_name='Buying type')),
                ('comment', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Comment for order')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='The time of ordering')),
                ('order_date', models.DateField(default=django.utils.timezone.now, verbose_name='Date of the ordering')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customer', verbose_name='Customer')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='orders',
            field=models.ManyToManyField(to='main.Order', verbose_name='Customer`s orders'),
        ),
    ]
