# Generated by Django 3.1 on 2020-10-26 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201026_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.customer', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='orders',
            field=models.ManyToManyField(blank=True, null=True, to='main.Order', verbose_name='Customer`s orders'),
        ),
    ]
