# Generated by Django 3.1 on 2020-10-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20201027_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Comment for order'),
        ),
    ]
